# Generated by Django 5.0.4 on 2024-04-25 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='specialty',
            new_name='breed',
        ),
    ]
